/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.11.1/samples
 * This project uses @Incubating APIs which are subject to change.
 */

dependencies {
    implementation 'com.pusher:pusher-java-client:2.4.1' // Replace with the latest stable version
}
